---
title: 'Inferential Statistics: Exploration of the Stroop Effect'
author: "Tyler C Julian"
date: "February 19, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Independent and Dependent variables

The __independent variable__ for this experiment would be the the conditions of the words. They change from congruent to incongruent between the two trials.

The __dependent variable__ would the the amount of time it takes a participant to complete the test. This is measured in seconds. 

### Hypothesis and Statistical Test

The __null hypothesis__ for this experiment is that there will not be a statistical difference in the average time between the congruent and incongruent conditions. 
The __alternative hypothesis__ is that there will be a statistical difference in the average time between the congruent and incongruent conditions.

These hypotheses can be pictured below, with _H~0~_ being the null hypothesis, _H~a~_ being the alternative hypothesis, _£g~c~_, being the average congruent time, and _£g~i~_ being the average incongruent time:

\begin{align}
H_0 : £g_c = £g_i \\
H_a : £g_c ¡Ú £g_i
\end{align}

The statistical test that will be used for this experiment is a two-tailed t-test. This t-test is a dependent t-test with paired samples, and is chosen because the population parameters are unknown. It is two-tailed because we are unsure whether the times will rise or fall between word conditions.

### Descriptive Statistics

### Visualizing the Dataset

### Two-Tailed T-Test and Conclusion

### Reflection